"use strict";(self.webpackChunkdoc_center=self.webpackChunkdoc_center||[]).push([[3640],{81536:(e,n,i)=>{i.r(n),i.d(n,{assets:()=>d,contentTitle:()=>s,default:()=>h,frontMatter:()=>t,metadata:()=>l,toc:()=>o});var r=i(74848),c=i(28453);const t={title:"Exception Handling"},s=void 0,l={id:"programming-languages/python/c-api/exceptions",title:"Exception Handling",description:"https://docs.python.org/3.11/c-api/exceptions.html",source:"@site/docs/00400-programming-languages/python/c-api/0500-exceptions.md",sourceDirName:"00400-programming-languages/python/c-api",slug:"/programming-languages/python/c-api/exceptions",permalink:"/dddtdd-docs/programming-languages/python/c-api/exceptions",draft:!1,unlisted:!1,tags:[],version:"current",lastUpdatedBy:"Colin Zuo",lastUpdatedAt:1720187019e3,sidebarPosition:500,frontMatter:{title:"Exception Handling"},sidebar:"docSidebar",previous:{title:"Reference Counting",permalink:"/dddtdd-docs/programming-languages/python/c-api/refcounting"},next:{title:"Operating System Utilities",permalink:"/dddtdd-docs/programming-languages/python/c-api/utilities-sys"}},d={},o=[{value:"Printing and clearing",id:"printing-and-clearing",level:2},{value:"Raising exceptions",id:"raising-exceptions",level:2},{value:"Issuing warnings",id:"issuing-warnings",level:2},{value:"Querying the error indicator",id:"querying-the-error-indicator",level:2},{value:"Signal Handling",id:"signal-handling",level:2},{value:"Exception Classes",id:"exception-classes",level:2},{value:"Exception Objects",id:"exception-objects",level:2},{value:"Standard Exceptions",id:"standard-exceptions",level:2},{value:"Standard Warning Categories",id:"standard-warning-categories",level:2}];function a(e){const n={a:"a",code:"code",h2:"h2",li:"li",p:"p",strong:"strong",ul:"ul",...(0,c.R)(),...e.components};return(0,r.jsxs)(r.Fragment,{children:[(0,r.jsx)(n.p,{children:(0,r.jsx)(n.a,{href:"https://docs.python.org/3.11/c-api/exceptions.html",children:"https://docs.python.org/3.11/c-api/exceptions.html"})}),"\n",(0,r.jsxs)(n.p,{children:["It works somewhat like the POSIX errno variable: there is a ",(0,r.jsx)(n.strong,{children:"global indicator (per thread)"})," of the last error that occurred."]}),"\n",(0,r.jsx)(n.p,{children:"If the error is not handled or carefully propagated, additional calls into the Python/C API may not behave as intended and may fail in mysterious ways."}),"\n",(0,r.jsxs)(n.p,{children:["The error indicator is not the result of ",(0,r.jsx)(n.code,{children:"sys.exc_info()"}),". The former corresponds to an exception that is not yet caught (and is therefore still propagating), while the latter returns an exception after it is caught (and has therefore stopped propagating)"]}),"\n",(0,r.jsx)(n.h2,{id:"printing-and-clearing",children:"Printing and clearing"}),"\n",(0,r.jsxs)(n.ul,{children:["\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"void PyErr_Clear()"})}),"\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"void PyErr_PrintEx(int set_sys_last_vars)"})}),"\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"void PyErr_WriteUnraisable(PyObject *obj)"})}),"\n"]}),"\n",(0,r.jsx)(n.h2,{id:"raising-exceptions",children:"Raising exceptions"}),"\n",(0,r.jsxs)(n.ul,{children:["\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"void PyErr_SetString(PyObject *type, const char *message)"})}),"\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"void PyErr_SetObject(PyObject *type, PyObject *value)"})}),"\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"PyObject *PyErr_Format(PyObject *exception, const char *format, ...)"})}),"\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"void PyErr_SetNone(PyObject *type)"})}),"\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"int PyErr_BadArgument()"})}),"\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"PyObject *PyErr_NoMemory()"})}),"\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"PyObject *PyErr_SetFromErrno(PyObject *type)"})}),"\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"PyObject *PyErr_SetImportError(PyObject *msg, PyObject *name, PyObject *path)"})}),"\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"void PyErr_BadInternalCall()"})}),"\n"]}),"\n",(0,r.jsx)(n.h2,{id:"issuing-warnings",children:"Issuing warnings"}),"\n",(0,r.jsxs)(n.ul,{children:["\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"int PyErr_WarnEx(PyObject *category, const char *message, Py_ssize_t stack_level)"})}),"\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"int PyErr_WarnFormat(PyObject *category, Py_ssize_t stack_level, const char *format, ...)"})}),"\n"]}),"\n",(0,r.jsx)(n.h2,{id:"querying-the-error-indicator",children:"Querying the error indicator"}),"\n",(0,r.jsxs)(n.ul,{children:["\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"PyObject *PyErr_Occurred()"})}),"\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"int PyErr_GivenExceptionMatches(PyObject *given, PyObject *exc)"})}),"\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"void PyErr_Fetch(PyObject **ptype, PyObject **pvalue, PyObject **ptraceback)"})}),"\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"void PyErr_Restore(PyObject *type, PyObject *value, PyObject *traceback)"})}),"\n"]}),"\n",(0,r.jsx)(n.h2,{id:"signal-handling",children:"Signal Handling"}),"\n",(0,r.jsxs)(n.ul,{children:["\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"int PyErr_CheckSignals()"})}),"\n"]}),"\n",(0,r.jsx)(n.h2,{id:"exception-classes",children:"Exception Classes"}),"\n",(0,r.jsxs)(n.ul,{children:["\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"PyObject *PyErr_NewException(const char *name, PyObject *base, PyObject *dict)"})}),"\n"]}),"\n",(0,r.jsx)(n.h2,{id:"exception-objects",children:"Exception Objects"}),"\n",(0,r.jsxs)(n.ul,{children:["\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"PyObject *PyException_GetTraceback(PyObject *ex)"})}),"\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"PyObject *PyException_GetContext(PyObject *ex)"})}),"\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"PyObject *PyException_GetCause(PyObject *ex)"})}),"\n"]}),"\n",(0,r.jsx)(n.h2,{id:"standard-exceptions",children:"Standard Exceptions"}),"\n",(0,r.jsxs)(n.p,{children:["All standard Python exceptions are available as global variables whose names are ",(0,r.jsx)(n.code,{children:"PyExc_"})," followed by the Python exception name. These have the type ",(0,r.jsx)(n.code,{children:"PyObject*"}),"; they are all class objects"]}),"\n",(0,r.jsxs)(n.ul,{children:["\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"PyExc_BaseException"})}),"\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"PyExc_Exception"})}),"\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"PyExc_ArithmeticError"})}),"\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"PyExc_IndexError"})}),"\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"PyExc_RuntimeError"})}),"\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"PyExc_StopIteration"})}),"\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"PyExc_SyntaxError"})}),"\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"PyExc_TimeoutError"})}),"\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"PyExc_TypeError"})}),"\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"PyExc_ValueError"})}),"\n"]}),"\n",(0,r.jsx)(n.h2,{id:"standard-warning-categories",children:"Standard Warning Categories"}),"\n",(0,r.jsxs)(n.ul,{children:["\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"PyExc_Warning"})}),"\n",(0,r.jsx)(n.li,{children:(0,r.jsx)(n.code,{children:"PyExc_DeprecationWarning"})}),"\n"]})]})}function h(e={}){const{wrapper:n}={...(0,c.R)(),...e.components};return n?(0,r.jsx)(n,{...e,children:(0,r.jsx)(a,{...e})}):a(e)}},28453:(e,n,i)=>{i.d(n,{R:()=>s,x:()=>l});var r=i(96540);const c={},t=r.createContext(c);function s(e){const n=r.useContext(t);return r.useMemo((function(){return"function"==typeof e?e(n):{...n,...e}}),[n,e])}function l(e){let n;return n=e.disableParentContext?"function"==typeof e.components?e.components(c):e.components||c:s(e.components),r.createElement(t.Provider,{value:n},e.children)}}}]);